In [49]:
from collections import Counter
from imblearn.datasets import fetch_datasets
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from imblearn.pipeline import make_pipeline as make_pipeline_imb
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import NearMiss
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import ComplementNB
from sklearn.metrics import confusion_matrix
from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold

In [33]:
data = pd.read_csv("DATA1.csv")
x=data[['koi_score','koi_period','koi_ror']]
y=data['O/P']
X_train, X_test, y_train, y_test = train_test_split(x,y,random_state=2)
len(X_train)
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           N       0.99      1.00      1.00      1986
           Y       0.00      0.00      0.00        12

    accuracy                           0.99      1998
   macro avg       0.50      0.50      0.50      1998
weighted avg       0.99      0.99      0.99      1998

[[1984    2]
 [  12    0]]


In [34]:
y_train.value_counts()
y_test.value_counts()


N    1986
Y      12
Name: O/P, dtype: int64

In [35]:
smt = SMOTE()
X_train_S, y_train_S = smt.fit_sample(X_train, y_train,)
lr = LogisticRegression()
lr.fit(X_train_S, y_train_S)
y_pred = lr.predict(X_test)
accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           N       1.00      0.85      0.92      1986
           Y       0.03      0.75      0.06        12

    accuracy                           0.85      1998
   macro avg       0.51      0.80      0.49      1998
weighted avg       0.99      0.85      0.91      1998



In [36]:
print(confusion_matrix(y_test,y_pred))

[[1689  297]
 [   3    9]]


In [37]:
kf = KFold(n_splits=10)
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    X_train_S, y_train_S = smt.fit_sample(X_train, y_train)
    lr.fit(X_train_S, y_train_S)
    y_pred = lr.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

0.8489778890279516
              precision    recall  f1-score   support

           N       1.00      0.85      0.92      2376
           Y       0.05      0.81      0.09        21

    accuracy                           0.85      2397
   macro avg       0.52      0.83      0.50      2397
weighted avg       0.99      0.85      0.91      2397

0.8602419691280767
              precision    recall  f1-score   support

           N       1.00      0.86      0.92      2373
           Y       0.05      0.67      0.09        24

    accuracy                           0.86      2397
   macro avg       0.52      0.76      0.51      2397
weighted avg       0.99      0.86      0.92      2397

0.8206090947017105
              precision    recall  f1-score   support

           N       1.00      0.82      0.90      2372
           Y       0.05      0.92      0.10        25

    accuracy                           0.82      2397
   macro avg       0.52      0.87      0.50      2397
weighted avg     

In [39]:
X_train_S, y_train_S = smt.fit_sample(X_train, y_train,)
clf = svm.SVC()
clf.fit(X_train_S, y_train_S)
y_pred = clf.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

0.8114309553608677
              precision    recall  f1-score   support

           N       1.00      0.81      0.89      2376
           Y       0.04      0.90      0.08        21

    accuracy                           0.81      2397
   macro avg       0.52      0.86      0.49      2397
weighted avg       0.99      0.81      0.89      2397

[[1926  450]
 [   2   19]]


In [40]:
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    X_train_S, y_train_S = smt.fit_sample(X_train, y_train)
    clf.fit(X_train_S, y_train_S)
    y_pred = clf.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

0.7801418439716312
              precision    recall  f1-score   support

           N       1.00      0.78      0.88      2374
           Y       0.04      0.91      0.07        23

    accuracy                           0.78      2397
   macro avg       0.52      0.85      0.47      2397
weighted avg       0.99      0.78      0.87      2397

0.7884856070087609
              precision    recall  f1-score   support

           N       1.00      0.79      0.88      2377
           Y       0.03      0.80      0.06        20

    accuracy                           0.79      2397
   macro avg       0.51      0.79      0.47      2397
weighted avg       0.99      0.79      0.87      2397

0.7939090529828953
              precision    recall  f1-score   support

           N       1.00      0.79      0.88      2381
           Y       0.03      0.88      0.05        16

    accuracy                           0.79      2397
   macro avg       0.51      0.83      0.47      2397
weighted avg     

In [46]:
X_train_S, y_train_S = smt.fit_sample(X_train, y_train,)
RF = RandomForestClassifier()
RF.fit(X_train_S, y_train_S)
y_pred = RF.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

0.9474342928660826
              precision    recall  f1-score   support

           N       0.99      0.95      0.97      2370
           Y       0.12      0.56      0.19        27

    accuracy                           0.95      2397
   macro avg       0.56      0.75      0.58      2397
weighted avg       0.98      0.95      0.96      2397

[[2256  114]
 [  12   15]]


In [44]:
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    X_train_S, y_train_S = smt.fit_sample(X_train, y_train)
    RF.fit(X_train_S, y_train_S)
    y_pred = RF.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

0.7922403003754693
              precision    recall  f1-score   support

           N       1.00      0.79      0.88      2379
           Y       0.03      0.83      0.06        18

    accuracy                           0.79      2397
   macro avg       0.51      0.81      0.47      2397
weighted avg       0.99      0.79      0.88      2397

0.7813934084272006
              precision    recall  f1-score   support

           N       1.00      0.78      0.88      2366
           Y       0.05      0.84      0.09        31

    accuracy                           0.78      2397
   macro avg       0.52      0.81      0.48      2397
weighted avg       0.99      0.78      0.87      2397

0.7818105965790572
              precision    recall  f1-score   support

           N       1.00      0.78      0.88      2380
           Y       0.03      0.94      0.06        17

    accuracy                           0.78      2397
   macro avg       0.51      0.86      0.47      2397
weighted avg     

In [52]:
gnb = ComplementNB()
gnb.fit(X_train, y_train)
y_pred = gnb.predict(X_test)
print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test,y_pred))

0.7943262411347518
              precision    recall  f1-score   support

           N       1.00      0.79      0.88      2370
           Y       0.04      0.78      0.08        27

    accuracy                           0.79      2397
   macro avg       0.52      0.79      0.48      2397
weighted avg       0.99      0.79      0.88      2397

[[1883  487]
 [   6   21]]


In [54]:
for train, test in kf.split(data):
    X_train, X_test, y_train, y_test = train_test_split(x,y,test_size = 0.3, shuffle = "true")
    gnb.fit(X_train, y_train)
    y_pred = gnb.predict(X_test)
    print(accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

0.8072590738423029
              precision    recall  f1-score   support

           N       1.00      0.81      0.89      2369
           Y       0.04      0.68      0.08        28

    accuracy                           0.81      2397
   macro avg       0.52      0.74      0.48      2397
weighted avg       0.98      0.81      0.88      2397

0.803087192323738
              precision    recall  f1-score   support

           N       0.99      0.81      0.89      2370
           Y       0.03      0.59      0.06        27

    accuracy                           0.80      2397
   macro avg       0.51      0.70      0.48      2397
weighted avg       0.98      0.80      0.88      2397

0.8114309553608677
              precision    recall  f1-score   support

           N       1.00      0.81      0.89      2370
           Y       0.04      0.70      0.08        27

    accuracy                           0.81      2397
   macro avg       0.52      0.76      0.49      2397
weighted avg      